name: Generate trophy

on:
  schedule:
    - cron: "0 0 * * *" # Runs once daily at midnight
      timezone: "Europe/London"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate stats card
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: ffasilva
          output_path:  profile/trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}
